server:
  port: 8080

frpc:
  provider:
    # rpc server
    serverAddress: 127.0.0.1:20880
    # zookeeper server
    registryAddress: 192.168.134.128:2181
    # registry center type, zookeeper/nacos/apoll/etcd/eureka
    registryType: zookeeper
    #registry loadbalance type: zkconsistenthash
    registryLoadBalanceType: random
    # reflect type, value is jdk or cglib
    reflectType: cglib
    # heartbeatInterval
    heartbeatInterval: 30000
    # scanNotActiveChannelInterval
    scanNotActiveChannelInterval: 60000