server:
  port: 8081

frpc:
  consumer:
    # zookeeper server
    registryAddress: 192.168.134.128:2181
    # registry center type, zookeeper/nacos/apoll/etcd/eureka
    registryType: zookeeper
    # registry loadbalance type: zkconsistenthash
    loadBalanceType: random
    # proxy type/javassist/jdk
    proxy: cglib
    # version
    version: 1.0.0
    # group
    group: default
    # zkconsistenthash
    serializationType: random
    # timeout
    timeout: 30000
    # async
    async: false
    # oneway
    oneway: false
    # heartbeatInterval
    heartbeatInterval: 30000
    # scanNotActiveChannelInterval
    scanNotActiveChannelInterval: 60000
    # retryInterval
    retryInterval: 1000
    # retryTimes
    retryTimes: 3